CREATE DATABASE gestion_projets CHARACTER SET utf8mb4;
USE gestion_projets;

CREATE TABLE IF NOT EXISTS projets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    statut VARCHAR(20) NOT NULL DEFAULT 'EN_COURS',
    date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_mise_a_jour DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS taches (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    titre VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    priorite VARCHAR(20) NOT NULL DEFAULT 'MOYENNE',
    statut VARCHAR(20) NOT NULL DEFAULT 'A_FAIRE',
    date_limite DATE NULL,
    date_mise_a_jour DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    projet_id BIGINT NOT NULL,
    CONSTRAINT fk_tache_projet FOREIGN KEY (projet_id) REFERENCES projets(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS documents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nom_fichier VARCHAR(255) NOT NULL,
    nom_original VARCHAR(255),
    type_contenu VARCHAR(255),
    chemin_stockage VARCHAR(500) NOT NULL,
    taille_fichier BIGINT,
    date_upload DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tache_id BIGINT NOT NULL,
    CONSTRAINT fk_document_tache FOREIGN KEY (tache_id) REFERENCES taches(id) ON DELETE CASCADE
);
